version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-portal-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://job-portal:;Rq^,y=2mzG=U+^@cluster0.t32indv.mongodb.net/job-portal?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=secret_key
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    container_name: job-portal-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
